id: IBAF99F77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:11:50+00:00'
last_modified: '2022-06-09T06:47:23.925909+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC323
  title: 'གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་སྤྱི་དོན་མདོར་བསྡུས་པ་ལེགས་བཤད་ནོར་བུའི་འོད་ཟེར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8612':
      image_group_id: I2PD18673
      title: Volume 1 of gsang sngags rdo rje theg pa'i spyi don nor bu'i 'od zer/
      total_pages: 200
      order: 1
      base_file: 8612.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
