id: IBAF99F77
legacy_id: P007866
ocr_import_info:
  bdrc_scan_id: W1AC323
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T01:10:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:06:35.970280+00:00'
last_modified: 2022-08-27 12:07:00.228833
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC323
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC323
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་སྤྱི་དོན་མདོར་བསྡུས་པ་ལེགས་བཤད་ནོར་བུའི་འོད་ཟེར།
  author: ཀུན་མཁྱེན་བཀྲ་ཤིས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9102688053007695
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2PD18673:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18673
      total_pages: 200
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18673.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9102688053007695
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
