id: P007866
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC323
  title: 'གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་སྤྱི་དོན་མདོར་བསྡུས་པ་ལེགས་བཤད་ནོར་བུའི་འོད་ཟེར། '
  author: ''
  volumes:
    940c63e214da48c189e4480a26637845:
      image_group_id: I2PD18673
      title: ''
      volume_number: 1
      total_pages: 200
ebook_metadata:
  title: 'གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་སྤྱི་དོན་མདོར་བསྡུས་པ་ལེགས་བཤད་ནོར་བུའི་འོད་ཟེར། '
  author: ''
  sku: P007866
  cover: cover.jpg
  layers:
  - pagination
